<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useSystemSettings } from '../composables/useSystemSettings'
import type { SystemFormDefinition } from '../types/system-settings'
import { usePortalSession } from '../../../core/auth/portal-session'

const { state, forms, loadForms, saveForm, removeForm } = useSystemSettings()
const { user } = usePortalSession()
const permissions = computed(() => new Set(user.value?.permissionCodes || []))
const dialogOpen = ref(false); const submitting = ref(false)
const form = reactive({ id: '', code: '', name: '', description: '', enabled: true, schemaText: '{\n  "type": "object",\n  "properties": {}\n}', version: 0 })
const open = (item?: SystemFormDefinition): void => { Object.assign(form, item ? { ...item, schemaText: JSON.stringify(item.schema || {}, null, 2) } : { id: '', code: '', name: '', description: '', enabled: true, schemaText: '{\n  "type": "object",\n  "properties": {}\n}', version: 0 }); dialogOpen.value = true }
const submit = async (): Promise<void> => { let schema: Record<string, unknown>; try { schema = JSON.parse(form.schemaText) } catch { ElMessage.warning('JSON Schema 格式错误'); return } submitting.value = true; try { await saveForm({ id: form.id || undefined, code: form.code, name: form.name, description: form.description, enabled: form.enabled, schema, version: form.version }); dialogOpen.value = false; ElMessage.success('表单已保存') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '保存失败') } finally { submitting.value = false } }
const remove = async (item: SystemFormDefinition): Promise<void> => { try { await ElMessageBox.confirm(`确定删除表单“${item.name}”吗？`, '删除确认', { type: 'warning' }); await removeForm(item); ElMessage.success('表单已删除') } catch (error) { if (error !== 'cancel') ElMessage.error(error instanceof Error ? error.message : '删除失败') } }
onMounted(() => void loadForms())
const formatTimestamp = (value?: string): string => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '-'
</script>

<template><div class="system-content"><section class="panel"><div class="panel-header"><div><h2 class="panel-title">表单管理</h2><div class="panel-subtitle">{{ forms.length }} 个表单定义</div></div><button v-if="permissions.has('asset:form:create')" class="btn primary" type="button" @click="open()">新增表单</button></div><div v-loading="state.loading" class="table-wrap"><table><thead><tr><th>编码</th><th>名称</th><th>说明</th><th>状态</th><th>版本</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in forms" :key="item.id"><td><code>{{ item.code }}</code></td><td>{{ item.name }}</td><td>{{ item.description || '-' }}</td><td><span class="tag" :class="item.enabled ? 'green' : 'gray'">{{ item.enabled ? '在用' : '已取消' }}</span></td><td>{{ item.version || 1 }}</td><td>{{ formatTimestamp(item.updatedAt) }}</td><td><button v-if="permissions.has('asset:form:update')" class="btn" type="button" @click="open(item)">编辑</button> <button v-if="permissions.has('asset:form:delete')" class="btn" type="button" @click="remove(item)">删除</button><span v-if="!permissions.has('asset:form:update') && !permissions.has('asset:form:delete')">-</span></td></tr><tr v-if="!forms.length" class="empty-row"><td colspan="7">当前范围内没有表单定义。</td></tr></tbody></table></div></section><el-alert v-if="state.errorMessage" type="error" :title="state.errorMessage" show-icon :closable="false" />
<el-dialog v-model="dialogOpen" :title="form.id ? '编辑表单' : '新增表单'" width="min(820px, 94vw)" append-to-body><el-form label-position="top" class="standard-form-grid"><el-form-item label="表单编码" required><el-input v-model="form.code" /></el-form-item><el-form-item label="表单名称" required><el-input v-model="form.name" /></el-form-item><el-form-item class="standard-form-wide" label="表单说明"><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled" /></el-form-item><el-form-item class="standard-form-wide" label="JSON Schema" required><el-input v-model="form.schemaText" type="textarea" :rows="14" /></el-form-item></el-form><template #footer><el-button @click="dialogOpen = false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">保存</el-button></template></el-dialog></div></template>
