<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Delete, Edit, Plus, Refresh } from '@element-plus/icons-vue'
import { useSystemSettings } from '../composables/useSystemSettings'
import type { SystemFormDefinition } from '../types/system-settings'

const { state, forms, loadForms, saveForm, removeForm } = useSystemSettings()
const dialogOpen = ref(false); const submitting = ref(false)
const form = reactive({ id: '', code: '', name: '', description: '', enabled: true, schemaText: '{\n  "type": "object",\n  "properties": {}\n}', version: 0 })
const open = (item?: SystemFormDefinition): void => { Object.assign(form, item ? { ...item, schemaText: JSON.stringify(item.schema || {}, null, 2) } : { id: '', code: '', name: '', description: '', enabled: true, schemaText: '{\n  "type": "object",\n  "properties": {}\n}', version: 0 }); dialogOpen.value = true }
const submit = async (): Promise<void> => { let schema: Record<string, unknown>; try { schema = JSON.parse(form.schemaText) } catch { ElMessage.warning('JSON Schema 格式错误'); return } submitting.value = true; try { await saveForm({ id: form.id || undefined, code: form.code, name: form.name, description: form.description, enabled: form.enabled, schema, version: form.version }); dialogOpen.value = false; ElMessage.success('表单已保存') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '保存失败') } finally { submitting.value = false } }
const remove = async (item: SystemFormDefinition): Promise<void> => { try { await ElMessageBox.confirm(`确定删除表单“${item.name}”吗？`, '删除确认', { type: 'warning' }); await removeForm(item); ElMessage.success('表单已删除') } catch (error) { if (error !== 'cancel') ElMessage.error(error instanceof Error ? error.message : '删除失败') } }
onMounted(() => void loadForms())
</script>

<template><section class="standard-business-view"><header class="standard-page-header"><div><h1>表单管理</h1><p>维护业务表单定义、状态和 JSON Schema。</p></div><div class="standard-header-actions"><el-button :icon="Refresh" @click="loadForms">刷新</el-button><el-button type="primary" :icon="Plus" @click="open()">新增表单</el-button></div></header><div class="standard-table-shell"><el-table v-loading="state.loading" :data="forms" height="100%" row-key="id"><el-table-column prop="name" label="表单名称" min-width="160" /><el-table-column prop="code" label="表单编码" min-width="150" /><el-table-column prop="description" label="说明" min-width="260" show-overflow-tooltip /><el-table-column label="状态" width="90"><template #default="scope"><el-tag :type="scope.row.enabled ? 'success' : 'info'">{{ scope.row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column prop="version" label="版本" width="80" /><el-table-column label="操作" width="150"><template #default="scope"><el-button link type="primary" :icon="Edit" @click="open(scope.row)">编辑</el-button><el-button link type="danger" :icon="Delete" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table></div><el-alert v-if="state.errorMessage" type="error" :title="state.errorMessage" show-icon :closable="false" />
<el-dialog v-model="dialogOpen" :title="form.id ? '编辑表单' : '新增表单'" width="min(820px, 94vw)" append-to-body><el-form label-position="top" class="standard-form-grid"><el-form-item label="表单编码" required><el-input v-model="form.code" /></el-form-item><el-form-item label="表单名称" required><el-input v-model="form.name" /></el-form-item><el-form-item class="standard-form-wide" label="表单说明"><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled" /></el-form-item><el-form-item class="standard-form-wide" label="JSON Schema" required><el-input v-model="form.schemaText" type="textarea" :rows="14" /></el-form-item></el-form><template #footer><el-button @click="dialogOpen = false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">保存</el-button></template></el-dialog></section></template>
